# ACM AI | Beginner Track Bonus Material: Intro to Tensorflow
Tensorflow is the framework of choice for many in the Machine Learning field. This intro should help you get started with using Tensorflow. 

## What is a tensor?

A tensor is an n-dimensional array. 

t1 = [1,2,3,4,5] is a 1-dimesional array,

t2 = [
[1,2,3,12],
[4,5,6,45],
[7,8,9,78]
] is a 2-dimensional array, ... etc.

### Rank of a tensor
A tensor's rank is the **number of dimensions** the tensor has. It is basically ***n***, in the above definition

### Shape of a tensor
The shape of a tensor is a **list specifying the number of items in each dimension**. In the above example, the shape of t1 is [5], while the shape of t2 is [3,4]. 

How is the size of the shape (yup, that makes sense) related to the rank?

## How Tensorflow works

Tensorflow uses a dataflow graph to represet a program. Every **edge** in the graph is a **Tensor**, every **node** is an **Operation**, and the Tensors "**flow**" from one Operation to the next. 

![](https://www.tensorflow.org/images/tensors_flowing.gif)

When you're writing a Tensorflow program, you're building this graph. But the Tensors in the graph (the edges) do not store the actual results of the Operations. The Tensors are just **handles**, telling the graph that a result is expected there. To actually get some actual results, you need to create a **Session** and **run** it. 

Let's get started

In [0]:
import tensorflow as tf
import numpy

In [45]:
#Let's define some constants.
c1 = tf.constant(42, dtype=tf.int32, shape = ()) # creates a tf.Operation that always produces the value 42. Returns a Tensor
c2 = tf.constant(13, dtype=tf.int32, shape = ()) # you can also create arrays by changing the shape parameter

#Let's multiply them
mult = tf.multiply(c1,c2) # c1 * c2 also works, * is overloaded

#Create a session
with tf.Session() as sess:
  print(sess.run(mult)) #To get the value of a Tensor or Operation, pass it into sess.run()

546


What if we don't know what values some input is going to take while writing the program.

We can create a **Placeholder**

In [0]:
p1 = tf.placeholder(tf.int32, shape=(2,3))
p2 = tf.placeholder(tf.int32, shape=(2,3))

add = p1 + p2 #why did we not have to use tf.add()? (Hint: overloading)

arr1 = numpy.ndarray((2,3))
arr2 = numpy.ndarray((2,3))
arr3 = numpy.ndarray((2,3))

for i in range(2):
  for j in range(3):
    arr1[i,j] = i + j
    arr2[i,j] = i * j
    arr3[i,j] = i ** j

In [47]:
with tf.Session() as sess:
  print(sess.run(add, feed_dict={p1:arr1, p2:arr2})) # need to specify the value for the placeholders while running

[[0 1 2]
 [1 3 5]]


In [48]:
with tf.Session() as sess:
  print(sess.run(add, feed_dict={p1:arr1, p2:arr3})) # with different p2

[[1 1 2]
 [2 3 4]]


Now what if we want to store data that is maintained across multiple run()s? We use **Variables**

Why would we need to maintain such data? 

In [0]:
var1 = tf.Variable([0,0,0]) # shape and data type of variable is determined by the initial value provided as argument

toAdd = tf.constant([1,1,1], dtype=tf.int32)

assign_op = tf.assign(var1, var1 + toAdd)

init_ = tf.global_variables_initializer() #before a variable can be used for the first time, it must be initialized


In [50]:
with tf.Session() as sess:
  sess.run(init_)
  for i in range(5):
    print(sess.run(assign_op))
    
#We see that the value of var1 persists across the multiple runs: it doesn't start off from [0,0,0] every time
#WARNING: We've used tf.assign() here, but it is slightly more complicated than it seems. 
#Things start getting weird when other operations depend on var1. You might expect the assign_op to run before, but it ends up not running
#We probably won't be using tf.assign() for anything other than explanatory purposes
#Come up and talk to us later if you're curious about this

[1 1 1]
[2 2 2]
[3 3 3]
[4 4 4]
[5 5 5]
